### ISSUE TITLE
Reaching out from OpenZeppelin

### ISSUE THREAD

**Issue by dbessinOZ** [sirhashalot/SCV-List#1]
Hey, I'm with OpenZeppelin helping build our tech teams. I would imagine you're comfortable doing what you do now considering your standing on Code4rena's leadearboard - in the spirit of being thorough with my job, though, I wanted to gauge your interest in potentially joining our audit/research team and audit with some of the biggest web3 protocols in the ecosystem. If not, no worries and thank you for all that you contribute to the space 🙂

**Comment by sirhashalot** [comment]
thank you for reaching out and I will keep this in mind
